-- MySQL Script generated by MySQL Workbench
-- Fri May 16 13:19:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema students_db_for_tgbot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `students_db_for_tgbot` ;

-- -----------------------------------------------------
-- Schema students_db_for_tgbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `students_db_for_tgbot` DEFAULT CHARACTER SET utf8 ;
USE `students_db_for_tgbot` ;

-- -----------------------------------------------------
-- Table `students_db_for_tgbot`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students_db_for_tgbot`.`user` ;

CREATE TABLE IF NOT EXISTS `students_db_for_tgbot`.`user` (
  `user_id` BIGINT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `students_db_for_tgbot`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students_db_for_tgbot`.`course` ;

CREATE TABLE IF NOT EXISTS `students_db_for_tgbot`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `students_db_for_tgbot`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students_db_for_tgbot`.`topic` ;

CREATE TABLE IF NOT EXISTS `students_db_for_tgbot`.`topic` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `topic_name` VARCHAR(255) NOT NULL,
  `position` INT NOT NULL,
  `text` TEXT NOT NULL,
  `difficulty` ENUM('beginner', 'intermediate', 'advanced') NOT NULL,
  PRIMARY KEY (`topic_id`, `course_id`),
  UNIQUE INDEX `topic_id_UNIQUE` (`topic_id` ASC) VISIBLE,
  INDEX `fk_topic_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_topic_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `students_db_for_tgbot`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `students_db_for_tgbot`.`user_has_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students_db_for_tgbot`.`user_has_topic` ;

CREATE TABLE IF NOT EXISTS `students_db_for_tgbot`.`user_has_topic` (
  `user_id` BIGINT NOT NULL,
  `topic_id` INT NOT NULL,
  `mark` INT NOT NULL,
  PRIMARY KEY (`user_id`, `topic_id`),
  INDEX `fk_user_has_topic_topic1_idx` (`topic_id` ASC) VISIBLE,
  INDEX `fk_user_has_topic_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_topic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `students_db_for_tgbot`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_topic_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `students_db_for_tgbot`.`topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
